### ISSUE TITLE
Val Result

### ISSUE THREAD

**Issue by vikyzeng** [poodarchu/Class-balanced-Grouping-and-Sampling-for-Point-Cloud-3D-Object-Detection#3]
I want to know the correspondence between result_val.json and Nuscenes sample_annotation.json in trainval set. It will help a lot when I apply your result in other tasks. 
Thanks for attention!

**Comment by poodarchu** [comment]
> I want to know the correspondence between result_val.json and Nuscenes sample_annotation.json in trainval set. It will help a lot when I apply your result in other tasks.
> Thanks for attention!

you can check the train/val split defined in nuscenes_devkit:
https://github.com/nutonomy/nuscenes-devkit/blob/f3594b967cbf42396da5c6cb08bd714437b53111/python-sdk/nuscenes/utils/splits.py#L102
